### ISSUE TITLE
Wrong channel image

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player-vue#15]
look at sugar-hiccup's image

https://mix.radio4000.com/
https://radio4000.com/sugar-hiccup

it seems that it s taking the wrong one in the array

**Comment by oskarrough** [comment]
https://github.com/internet4000/radio4000-player-vue/blob/master/src/store.js#L29

**Comment by hugurp** [comment]
i guess we're starting to have "some" images issue.
Maybe to fix them all we can spend some time changing the way we store them in the DB

**Comment by oskarrough** [comment]
https://github.com/internet4000/radio4000-api/issues/7

**Comment by oskarrough** [comment]
One example is https://radio4000.com/bausteinwerk-reiter-a36-c. It has an image on R4 but not in the vue player.

correct: https://res.cloudinary.com/radio4000/image/upload/p5ypwqk8jyx0fe6czlmc
wrong: https://res.cloudinary.com/radio4000/image/upload/byhlo8oznwsoak2oycfb
