### ISSUE TITLE
PORT - which port for development and production

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player-vue#24]
This thread is opened on each project to think about a common implementation accros `Radio4000` projects.

# PORT - which port for development and production should all r4 projects use

For each projects we need different ports, to test them simultaneously:
- development
- production
- testing

ex: use the `radio4000-player-vue` localhost as source for all projects using it, and test changes on each of them.

## development
4000: [r4](https://github.com/internet4000/radio4000-api/issues/13) <- here now
4001: r4-api 
4002: r4-player
4003: r4-embed-api

## production

Should that be decided too?
- for back-end (express) projects
- for front-end (ember.js, vue.js, react.js)

## testing

How do each testing frameworks run tests? On which ports?

**Comment by oskarrough** [comment]
changed port to 4002 https://github.com/internet4000/radio4000-player-vue/commit/661cbd5b7108d492d48d516ea17bfc7779117126

**Comment by oskarrough** [comment]
@hugurp we can close this one now, right?
