### ISSUE TITLE
Naming for this project

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player-vue#3]
Rename this component to what?

- `radio4000-embed` ?

but when our goal is a web-component is embed the right name?

**Comment by hugovieilledent** [comment]
not sure about that anymore
are we just doing an embed-player or a player for r4?
no rush, maybe we can wait

**Comment by oskarrough** [comment]
Now I think of it as a player for single Radio4000 channels. A reusable web component that can either

- be embedded via an iframe (limited customization, optional skins)
- inserted directly as a web component (full customization, api to control the player from outside via events)
