### ISSUE TITLE
Responsive styles

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player-vue#35]
Currently the track-list has a fixed height. To make the player easier to put on your own site it should adapt, as far as possible, to whichever size it has. Should be gg with flexbox!

Header = fixed to two lines of text
Video = aspect ratio with min + max height
Track list = takes up available space
Footer/menu = fixed to "1 line of text" height

**Comment by hugurp** [comment]
yes

**Comment by oskarrough** [comment]
closedhttps://github.com/internet4000/radio4000-player-vue/pull/37/
