### ISSUE TITLE
Muting the youtube player doesn't reflect in our state

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player-vue#47]
Muting YouTube via their interface doesn't update our own `isMuted` CP. Let's check why.

**Comment by hugurp** [comment]
Think it is cuz, their mute does not set the volume to 0, but mutes it

**Comment by hugurp** [comment]
I think we can close this as there are no event triggered by `mute` on the youtube player.
I upgraded our code to unmute the player at every new session
