### ISSUE TITLE
current version in master does not auto-play

### ISSUE THREAD

**Issue by hugurp** [Internet4000/radio4000-player-vue#6]
I don't get where it comes from.

- On http://200okrecords.com
At the end of a video the next one in inserted but does not load (youtube loader keeps spinning).
- Locally I can't get the the app to work.
Server runs but
`Error: Cannot find module 'vue-custom-element' from '~/Code/internet4000/radio4000-player-vue/src'`

What seems to have happended is that this project is not setup to deploy on production branch but master

I am thinking:
- [x] let's fix autoplay
- [ ] create production branch
- [ ] setup netlify with production branch

**Comment by oskarrough** [comment]
I think autoplay was fixed in a7692eeac23ab23fc062abff14a41f3e18883ad7.

**Comment by oskarrough** [comment]
For how to deploy we can continue in https://github.com/Internet4000/radio4000-player-vue/issues/5
