### ISSUE TITLE
track-list-manipulation, reverse array and more methods

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player-vue#7]
- [x] reverse array so the top track is the latest added
- [ ] what system do we use introduce shuffle, and more `track-list-manipulation` methods

**Comment by oskarrough** [comment]
The reversed (= sorted) array could be a computed property in the `tracks-list` component.

For shuffle we use this on R4:

```js
// Takes an array and returns a shuffled version.
// It uses this algorithm: http://bost.ocks.org/mike/shuffle/
export function shuffleArray(array) {
	// Return a new array.
	array = array.slice();

	let m = array.length;
	let t;
	let i;

	// While there remain elements to shuffle…
	while (m) {
		// Pick a remaining element…
		i = Math.floor(Math.random() * m--);

		// And swap it with the current element.
		t = array[m];
		array[m] = array[i];
		array[i] = t;
	}
	return array;
}
```

**Comment by oskarrough** [comment]
Closing here, since reversed tracks are in, and opening a separate issue for shuffle: https://github.com/internet4000/radio4000-player-vue/issues/16
