### ISSUE TITLE
prevent player from jumping in width

### ISSUE THREAD

**Issue by hugurp** [Internet4000/radio4000-player-vue#8]
on load for exemple, https://200okrecords.com/
the player jumps in width

**Comment by oskarrough** [comment]
I think part of solving this is to either use shadow DOM or the iframe-version by default. Otherwise we can not guarantee that the styles won't be overwritten by whatever is on that page.

Or we need

```
radio4000-player {
  width: 320px;
}
```

Because we don't specify any width otherwise, only min-width.

**Comment by oskarrough** [comment]
Will be fixed by https://github.com/Internet4000/radio4000-player-vue/pull/10
